export const products = [
    {
        productId: 1,
        name: 'New Balance 9060',
        price: 100,
        image: 'https://nb.scene7.com/is/image/NB/u9060blk_nb_02_i?$pdpflexf2$&wid=464&hei=464',
        category: 'unisex',
        description: 'The 9060 is a modern take on the classic 900 series, featuring a sleeker silhouette and a more minimalist design.',
        weight: 0.5,
        size: '8.5',
        color: 'black',
        quantity: 10,
        rating: 4.5,
    }
,
    {
        productId: 2,
        name: 'Nike Air Max 270',
        price: 150,
        image: 'https://nb.scene7.com/is/image/NB/mr530sg_nb_02_i?$pdpflexf2$&wid=464&hei=464',
        category: 'men',
        description: 'Nike\'s first lifestyle Air Max brings you style, comfort and big attitude in the Nike Air Max 270.',
        weight: 0.6,
        size: '9',
        color: 'white',
        quantity: 15,
        rating: 4.8
    },
    {
        productId: 3,
        name: 'Adidas Ultraboost 22',
        price: 180,
        image: 'https://nb.scene7.com/is/image/NB/ws327fe_nb_02_i?$pdpflexf2$&wid=464&hei=464',
        category: 'women',
        description: 'Responsive running shoes made in part with Parley Ocean Plastic.',
        weight: 0.4,
        size: '7',
        color: 'black',
        quantity: 8,
        rating: 4.7
    },
    {
        productId: 4,
        name: 'Puma RS-X',
        price: 120,
        image: 'https://nb.scene7.com/is/image/NB/u9060wht_nb_02_i?$pdpflexf2$&wid=464&hei=464',
        category: 'unisex',
        description: 'Running System sneakers with bold design and premium cushioning.',
        weight: 0.55,
        size: '8',
        color: 'multi',
        quantity: 12,
        rating: 4.3
    },
    {
        productId: 5,
        name: 'Reebok Classic Leather',
        price: 80,
        image: 'https://nb.scene7.com/is/image/NB/ml574evg_nb_02_i?$pdpflexf2$&wid=464&hei=464',
        category: 'unisex',
        description: 'Timeless athletic style with soft leather upper and EVA midsole.',
        weight: 0.45,
        size: '8.5',
        color: 'white',
        quantity: 20,
        rating: 4.6
    },
    {
        productId: 6,
        name: 'ASICS Gel-Nimbus 24',
        price: 160,
        image: 'https://nb.scene7.com/is/image/NB/m1906rer_nb_02_i?$pdpflexf2$&wid=464&hei=464',
        category: 'men',
        description: 'Premium neutral running shoe with excellent cushioning and comfort.',
        weight: 0.52,
        size: '9.5',
        color: 'grey',
        quantity: 7,
        rating: 4.9
    }
]