
const initialProductData = [
    {
      id: 1,
      name: "Wireless Mouse",
      quantity: 45,
      price: 29.99,
      rating: 4.5,
      category: "Electronics",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 2,
      name: "Bluetooth Headphones",
      quantity: 23,
      price: 59.99,
      rating: 4.8,
      category: "Electronics",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 3,
      name: "Coffee Maker",
      quantity: 15,
      price: 89.99,
      rating: 4.3,
      category: "Home Appliances",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 4,
      name: "Electric Kettle",
      quantity: 32,
      price: 19.99,
      rating: 4.0,
      category: "Home Appliances",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 5,
      name: "Smartphone Stand",
      quantity: 60,
      price: 14.99,
      rating: 4.7,
      category: "Accessories",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 6,
      name: "Wireless Mouse",
      quantity: 45,
      price: 29.99,
      rating: 4.5,
      category: "Electronics",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 7,
      name: "Wireless ",
      quantity: 45,
      price: 29.99,
      rating: 4.5,
      category: "Electronics",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 8,
      name: "Wireless Mouse",
      quantity: 45,
      price: 29.99,
      rating: 4.5,
      category: "Electronics",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 9,
      name: "Wireless Mouse",
      quantity: 45,
      price: 29.99,
      rating: 4.5,
      category: "Electronics",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
    {
      id: 10,
      name: "Wireless Mouse",
      quantity: 45,
      price: 29.99,
      rating: 4.5,
      category: "wf",
      size: "S",
      weight: "45",
      color: "Red",
      description: "Tommy Hilfiger men striped pink sweatshirt. Crafted with cotton. Material composition is 100% organic cotton. This is one of the world’s leading designer lifestyle brands and is internationally recognized for celebrating the essence of classic American cool style, featuring preppy with a twist designs.",
      discount: 0,
    },
  ];

export default initialProductData;